import fs from 'fs-extra';
import path from 'path';
import { INTENT_CATEGORIES, REQUIRED_PAGES } from '../utils/constants.js';

export async function createSeomdDir(cwd, answers) {
    const { site_type, brand, domain, competitors } = answers;
    const pages = REQUIRED_PAGES[site_type] || REQUIRED_PAGES.saas;
    const seomdDir = path.join(cwd, '.seomd');

    await fs.ensureDir(path.join(seomdDir, 'intent'));
    await fs.ensureDir(path.join(seomdDir, 'competitors'));
    await fs.ensureDir(path.join(seomdDir, 'pages'));
    await fs.ensureDir(path.join(seomdDir, 'pages', 'md'));
    await fs.ensureDir(path.join(seomdDir, 'pages', 'templates'));
    await fs.ensureDir(path.join(seomdDir, 'reports'));
    await fs.ensureDir(path.join(seomdDir, 'generated'));

    await fs.writeFile(
        path.join(seomdDir, 'README.md'),
        generateSeomdReadme(brand, domain),
        'utf8'
    );

    await fs.writeFile(path.join(seomdDir, 'index.md'), generateSeomdIndex(brand, domain), 'utf8');
    await fs.writeFile(path.join(seomdDir, 'meta.yaml'), generateMeta(), 'utf8');

    await fs.writeFile(path.join(seomdDir, 'intent', 'index.yaml'), generateIntentIndex(), 'utf8');
    for (const intent of INTENT_CATEGORIES) {
        await fs.writeFile(path.join(seomdDir, 'intent', `${intent}.md`), generateIntentPlaceholder(intent), 'utf8');
    }

    const competitorList = Array.isArray(competitors) ? competitors : [];
    await fs.writeFile(
        path.join(seomdDir, 'competitors', 'index.yaml'),
        generateCompetitorIndex(competitorList),
        'utf8'
    );

    await fs.writeFile(
        path.join(seomdDir, 'pages', 'pinned.md'),
        generatePinnedPages(pages),
        'utf8'
    );

    for (const page of pages) {
        await fs.writeFile(
            path.join(seomdDir, 'pages', 'md', `${page.id}.md`),
            generatePagePlaceholder(page, brand),
            'utf8'
        );
    }

    const date = new Date().toISOString().split('T')[0];
    await fs.writeFile(
        path.join(seomdDir, 'reports', `${date}.md`),
        generateInitialReport(brand, domain, date),
        'utf8'
    );

    await fs.writeFile(
        path.join(seomdDir, 'generated', 'latest-summary.yaml'),
        generateLatestSummary(),
        'utf8'
    );
}

function generateSeomdReadme(brand, domain) {
    return `# .seomd/

Intelligence directory for ${brand} (${domain})
Generated by SEO.md CLI — https://seomd.dev

## Directory Structure

\`\`\`
.seomd/
├── index.md
├── meta.yaml
├── intent/         # intent clusters (index + docs)
├── competitors/    # competitor dossiers (index + docs)
├── pages/          # page registry and deep dives
├── reports/        # dated snapshot reports (gitignored by default)
└── generated/      # platform generated summaries and caches
\`\`\`

## Usage

\`\`\`bash
# Run citation analysis and update all files
npx seomd analyze

# Sync latest platform intelligence
npx seomd sync

# View current status
npx seomd status
\`\`\`

## File Ownership

- \`pages/\` — platform generated, do not edit manually
- \`reports/\` — platform generated, gitignored by default
- \`competitors/\` — platform generated, do not edit manually

Connect your platform at https://seomd.dev/connect
`;
}

function generateSeomdIndex(brand, domain) {
    return `# .seomd Index

This directory is the structured knowledge base for ${brand} (${domain}).

## Start Here

- Strategy: intent clusters in \`intent/\`
- Competitive landscape: competitor dossiers in \`competitors/\`
- Pages:
  - Curated: \`pages/pinned.md\`
  - Deep dives: \`pages/md/\`
  - Registry: \`pages/pages.db\` (planned)
- Reports: \`reports/\`

## Ownership

- Founder edits: \`intent/\`, \`pages/pinned.md\` (recommended)
- Platform generates: \`reports/\`, \`generated/\`, \`pages/md/\` (when requested)
`;
}

function generateMeta() {
    return `schema_version: 2
generated_at: ${new Date().toISOString()}
tool: seomd-cli
`;
}

function generateIntentIndex() {
    return `version: 1
intents:
  - id: informational
    title: Informational
    file: informational.md
    owner: founder
  - id: comparison
    title: Comparison
    file: comparison.md
    owner: founder
  - id: transactional
    title: Transactional
    file: transactional.md
    owner: founder
  - id: reputational
    title: Reputational
    file: reputational.md
    owner: founder
  - id: category
    title: Category
    file: category.md
    owner: founder
`;
}

function generateIntentPlaceholder(intent) {
    return `# ${intent}

## Founder

- Priority:
- Target queries:
- Positioning constraints:
- Do:
- Don’t:

## Platform

- Last analyzed:
- Citation rate:
- Gap score:
- Top cited competitors:
`;
}

function getCompetitorId(domain) {
    return String(domain)
        .replace(/^(https?:\/\/)?(www\.)?/, '')
        .replace(/\/.*$/, '')
        .replace(/\.[a-z]{2,6}(\.[a-z]{2,6})?$/i, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

function generateCompetitorIndex(competitors) {
    const entries = (competitors || [])
        .filter(Boolean)
        .map(c => {
            const id = getCompetitorId(c);
            return `  - id: ${id || 'competitor'}
    domain: ${c}
    file: ${id || 'competitor'}.md
    status: active`;
        })
        .join('\n');

    return `version: 1
competitors:
${entries || '  []'}
`;
}

function generatePinnedPages(pages) {
    const lines = pages.map(p => `- id: ${p.id}\n  url: ${p.url}\n  md: pages/md/${p.id}.md`).join('\n');
    return `# Pinned Pages

This file is a small, curated list of the most important pages.

${lines}
`;
}

function generatePagePlaceholder(page, brand) {
    return `# ${page.id}

## Page: ${page.url}

### Priority: ${page.priority}

### Last analyzed: null

### Run \`npx seomd analyze --page ${page.url}\` to populate

brand: "${brand}"
page_id: ${page.id}
url: ${page.url}
status: planned
citation_rate: null
gap_score: null
top_cited_competitor: null
last_analyzed: null

why_page_won: []
citation_hooks: []
gaps_for_brand: []
remediation_playbook: []

fastest_win:
  action: null
  estimated_gap_score_improvement: null
  effort: null

suggested_content_outline: []
`;
}

function generateInitialReport(brand, domain, date) {
    return `# SEO.md Report — ${date}

## ${brand} (${domain})

### Initial report — run \`npx seomd analyze\` to populate

date: ${date}
brand: "${brand}"
domain: ${domain}
overall_citation_rate: null
overall_gap_score: null

intent_summary:
  informational: null
  comparison: null
  transactional: null
  reputational: null
  category: null

top_opportunities: []
completed_wins: []
`;
}

function generateLatestSummary() {
    return `last_analyzed: null
overall_citation_rate: null
overall_gap_score: null
top_opportunities: []
`;
}
