import fs from 'fs-extra';
import path from 'path';
import { REQUIRED_PAGES } from '../utils/constants.js';

export async function createSeomdDir(cwd, answers) {
    const { site_type, brand, domain } = answers;
    const pages = REQUIRED_PAGES[site_type] || REQUIRED_PAGES.saas;
    const seomdDir = path.join(cwd, '.seo');

    // Create directory structure
    await fs.ensureDir(path.join(seomdDir, 'pages'));

    // Create README inside .seo/
    await fs.writeFile(
        path.join(seomdDir, 'README.md'),
        generateSeomdReadme(brand, domain),
        'utf8'
    );

    // Create placeholder page files
    for (const page of pages) {
        await fs.writeFile(
            path.join(seomdDir, 'pages', `${page.id}.md`),
            generatePagePlaceholder(page, brand),
            'utf8'
        );
    }
}

function generateSeomdReadme(brand, domain) {
    return `# .seo/

AI search optimization workspace for **${brand}** (${domain})
Generated by SEO.md CLI — https://seomd.dev

## What is this?

\`.seo/\` stores platform-generated intelligence from citation audits, competitor analysis, and reverse-engineered playbooks. It lives alongside your source code so SEO strategy is version-controlled and reviewable in PRs.

## Directory Structure

\`\`\`
.seo/
├── pages/          # per-page reverse-engineer analysis
├── STATUS.yml      # gap scores and citation metrics (platform generated)
└── REVERSE.md      # competitor playbooks (platform generated)
\`\`\`

## Git behavior

| Path | Git | Why |
|------|-----|-----|
| \`.seo/pages/\` | tracked | actionable playbooks belong in code review |
| \`.seo/STATUS.yml\` | tracked | gap scores represent current project state |
| \`.seo/REVERSE.md\` | tracked | competitor intel is project state |

## How to configure SEO.md

\`SEO.md\` is your declarative configuration file. It tells the AI optimization platform exactly what you care about. Here is a guide on how to fill it out:

### 1. Intent (Queries)
Add queries your buyers actually type into AI engines. Think about what someone asks ChatGPT or Perplexity when they are looking for a solution like yours.

### 2. Pages
Declare the key pages on your site. For each page, set its priority and status (\`live | draft | planned\`). The platform will scan these and generate playbooks for each one.

### 3. AI Engine Optimization (AEO) Rules
Set the strict guidelines you want your writers or AI to follow (e.g. \`answer_first_format: true\`).

### 4. Platform Connection
To enable live writebacks, connect your platform:
1. Connect at https://seomd.dev/connect
2. Add \`SEOMD_API_KEY\` to your \`.env\`
3. Run \`npx seomd analyze\`

**Note: Never commit your API key to version control.**

## When to run what

\`\`\`bash
# First full audit — scans all pages + intents
npx seomd analyze

# Refresh from cached platform data (no new scan)
npx seomd sync

# Check current gap scores without modifying files
npx seomd status
npx seomd status --json
\`\`\`

| Command | Use when |
|---------|----------|
| \`analyze\` | You want a fresh audit, new competitor data, or updated playbooks |
| \`sync\` | You just want the latest cached data from your platform |
| \`status\` | You want a quick health check without writebacks |

## Reading a page playbook

Each \`pages/<id>.md\` contains:

- **why_page_won** — what top-cited competitors do right
- **citation_hooks** — patterns to replicate
- **gaps_for_brand** — where your page falls short
- **remediation_playbook** — step-by-step fixes with effort/impact
- **fastest_win** — highest ROI action to take now
- **suggested_content_outline** — ready-to-use outline for your writer or AI

## File ownership

| File/dir | Owner | Editable? |
|-----------|-------|----------|
| \`SEO.md\` | you | yes |
| \`.seo/STATUS.yml\` | platform | no |
| \`.seo/REVERSE.md\` | platform | no |
| \`.seo/pages/*.md\` | platform | no |

Platform-generated files are overwritten on each \`analyze\` or \`sync\`.
`;
}

function generatePagePlaceholder(page, brand) {
    const date = new Date().toISOString().split('T')[0];
    return `# ${page.id}

## Page: ${page.url}

### Priority: ${page.priority}

### Last analyzed: null

### Run \`npx seomd analyze --page ${page.url}\` to populate

brand: "${brand}"
page_id: ${page.id}
url: ${page.url}
status: planned
citation_rate: null
gap_score: null
top_cited_competitor: null
last_analyzed: null

why_page_won: []
citation_hooks: []
gaps_for_brand: []
remediation_playbook: []

fastest_win:
  action: null
  estimated_gap_score_improvement: null
  effort: null

suggested_content_outline: []
`;
}
