import fs from 'fs-extra';
import path from 'path';
import { REQUIRED_PAGES } from '../utils/constants.js';

export async function createSeomdDir(cwd, answers) {
    const { site_type, brand, domain } = answers;
    const pages = REQUIRED_PAGES[site_type] || REQUIRED_PAGES.saas;
    const seomdDir = path.join(cwd, '.seomd');

    // Create directory structure
    await fs.ensureDir(path.join(seomdDir, 'pages'));
    await fs.ensureDir(path.join(seomdDir, 'reports'));
    await fs.ensureDir(path.join(seomdDir, 'competitors'));

    // Create README inside .seomd/
    await fs.writeFile(
        path.join(seomdDir, 'README.md'),
        generateSeomdReadme(brand, domain),
        'utf8'
    );

    // Create placeholder page files
    for (const page of pages) {
        await fs.writeFile(
            path.join(seomdDir, 'pages', `${page.id}.md`),
            generatePagePlaceholder(page, brand),
            'utf8'
        );
    }

    // Create initial empty report
    const date = new Date().toISOString().split('T')[0];
    await fs.writeFile(
        path.join(seomdDir, 'reports', `${date}.md`),
        generateInitialReport(brand, domain, date),
        'utf8'
    );
}

function generateSeomdReadme(brand, domain) {
    return `# .seomd/

Intelligence directory for ${brand} (${domain})
Generated by seomd CLI — https://seomd.dev

## Directory Structure

\`\`\`
.seomd/
├── pages/          # per-page reverse engineer analysis
├── reports/        # dated snapshot reports (gitignored by default)
└── competitors/    # competitor citation profiles
\`\`\`

## Usage

\`\`\`bash
# Run citation analysis and update all files
npx seomd analyze

# Sync latest platform intelligence
npx seomd sync

# View current status
npx seomd status
\`\`\`

## File Ownership

- \`pages/\` — platform generated, do not edit manually
- \`reports/\` — platform generated, gitignored by default
- \`competitors/\` — platform generated, do not edit manually

Connect your platform at https://seomd.dev/connect
`;
}

function generatePagePlaceholder(page, brand) {
    const date = new Date().toISOString().split('T')[0];
    return `# ${page.id}
# Page: ${page.url}
# Priority: ${page.priority}
# Last analyzed: null
# ─────────────────────────────────────────────
# Run \`npx seomd analyze --page ${page.url}\` to populate

brand: "${brand}"
page_id: ${page.id}
url: ${page.url}
status: planned
citation_rate: null
gap_score: null
top_cited_competitor: null
last_analyzed: null

why_page_won: []
citation_hooks: []
gaps_for_brand: []
remediation_playbook: []

fastest_win:
  action: null
  estimated_gap_score_improvement: null
  effort: null

suggested_content_outline: []
`;
}

function generateInitialReport(brand, domain, date) {
    return `# SEO.md Report — ${date}
# ${brand} (${domain})
# ─────────────────────────────────────────────
# Initial report — run \`npx seomd analyze\` to populate

date: ${date}
brand: "${brand}"
domain: ${domain}
overall_citation_rate: null
overall_gap_score: null

intent_summary:
  informational: null
  comparison: null
  transactional: null
  reputational: null
  category: null

top_opportunities: []
completed_wins: []
`;
}