import fs from 'fs-extra';
import path from 'path';
import YAML from 'yaml';
import { writeSeoMd } from './parser.js';

/**
 * Merges platform analysis blocks back into the SEO.md YAML document.
 * 
 * @param {YAML.Document} doc - The YAML Document of SEO.md
 * @param {any} response - The API response from analyze/sync
 * @param {string} cwd - Current working directory
 */
export async function writeAnalysisToSeoMd(doc, response, cwd) {
    const lastAnalyzed = response.aeo_analysis.last_analyzed;
    const nextAnalysis = response.aeo_analysis.next_analysis;

    // 1. Update AEO analysis
    doc.setIn(['aeo', '_analysis', 'source'], 'foxcite');
    doc.setIn(['aeo', '_analysis', 'overall_citation_rate'], response.aeo_analysis.overall_citation_rate);
    doc.setIn(['aeo', '_analysis', 'overall_gap_score'], response.aeo_analysis.overall_gap_score);
    doc.setIn(['aeo', '_analysis', 'engines_tracked'], response.aeo_analysis.engines_tracked);
    doc.setIn(['aeo', '_analysis', 'last_analyzed'], lastAnalyzed);
    doc.setIn(['aeo', '_analysis', 'next_analysis'], nextAnalysis);

    // 2. Update Intent analysis
    doc.setIn(['intent', '_analysis', 'source'], 'foxcite');
    doc.setIn(['intent', '_analysis', 'last_analyzed'], lastAnalyzed);
    doc.setIn(['intent', '_analysis', 'next_analysis'], nextAnalysis);

    const categories = ['informational', 'comparison', 'transactional', 'reputational', 'category'];
    for (const cat of categories) {
        if (response.intent_analysis && response.intent_analysis[cat]) {
            doc.setIn(['intent', '_analysis', cat, 'citation_rate'], response.intent_analysis[cat].citation_rate);
            doc.setIn(['intent', '_analysis', cat, 'top_cited_competitor'], response.intent_analysis[cat].top_cited_competitor);
            doc.setIn(['intent', '_analysis', cat, 'gap_score'], response.intent_analysis[cat].gap_score);
            doc.setIn(['intent', '_analysis', cat, 'trend'], response.intent_analysis[cat].trend || 'stable');
        }
    }

    // 3. Update Pages analysis
    doc.setIn(['pages', '_analysis', 'source'], 'foxcite');
    doc.setIn(['pages', '_analysis', 'last_analyzed'], lastAnalyzed);

    const pageSummaries = response.page_analysis.map(p => ({
        id: p.id,
        url: p.url,
        citation_rate: p.citation_rate,
        gap_score: p.gap_score,
        top_cited_competitor: p.top_cited_competitor
    }));
    doc.setIn(['pages', '_analysis', 'pages'], pageSummaries);
    doc.setIn(['pages', '_analysis', 'missing_pages'], []);
    doc.setIn(['pages', '_analysis', 'build_order_recommendation'], []);

    // 4. Update Keywords analysis
    doc.setIn(['keywords', '_analysis', 'source'], 'foxcite');
    doc.setIn(['keywords', '_analysis', 'last_analyzed'], lastAnalyzed);
    doc.setIn(['keywords', '_analysis', 'next_analysis'], nextAnalysis);

    // Write back to SEO.md
    await writeSeoMd(doc, cwd);
}

/**
 * Generates and writes the SEO.REVERSE.md file.
 * 
 * @param {string} cwd - Current working directory
 * @param {any} response - The API response from analyze/sync
 */
export async function writeReverseMd(cwd, response, defaultDomain = 'example.com', defaultBrand = 'My Brand') {
    const reversePath = path.join(cwd, 'SEO.REVERSE.md');

    const reversePages = response.page_analysis.map(p => ({
        id: p.id,
        url: p.url,
        status: p.status || 'planned',
        citation_rate: p.citation_rate,
        gap_score: p.gap_score,
        top_cited_competitor: p.top_cited_competitor,
        why_page_won: p.why_page_won || [],
        citation_hooks: p.citation_hooks || [],
        gaps_for_my_brand: p.gaps_for_brand || [],
        remediation_playbook: p.remediation_playbook || [],
        fastest_win: p.fastest_win || { action: null, estimated_gap_score_improvement: null, effort: null },
        suggested_content_outline: p.suggested_content_outline || []
    }));

    const primaryCompetitor = response.intent_analysis?.comparison?.top_cited_competitor || 'None';

    const reverseDoc = {
        domain: response.domain || defaultDomain,
        brand: response.brand_name || defaultBrand,
        primary_competitor: primaryCompetitor,
        last_analyzed: response.aeo_analysis.last_analyzed,
        next_analysis: response.aeo_analysis.next_analysis,
        source: 'foxcite',
        pages: reversePages
    };

    const header = `# SEO.REVERSE.md
#
# This file is generated by the foxcite platform.
# Do not edit manually — run \`npx seomd analyze\` to update.
# Run \`npx seomd sync\` to pull latest intelligence.

`;

    const yamlContent = YAML.stringify(reverseDoc);
    await fs.writeFile(reversePath, header + yamlContent, 'utf8');
}

/**
 * Writes individual page playbooks into .seo/pages/{id}.md files.
 * 
 * @param {string} cwd - Current working directory
 * @param {any} response - The API response from analyze/sync
 */
export async function writePageAnalysis(cwd, response) {
    const seomdDir = path.join(cwd, '.seo');
    const pagesDir = path.join(seomdDir, 'pages');

    await fs.ensureDir(pagesDir);

    for (const page of response.page_analysis) {
        if (page.markdown_content) {
            const filePath = path.join(pagesDir, `${page.id}.md`);
            await fs.writeFile(filePath, page.markdown_content, 'utf8');
        }
    }
}
