import fs from 'fs-extra';
import path from 'path';
import YAML from 'yaml';

/**
 * Writes platform analysis blocks into the .seo/STATUS.yml file.
 * 
 * @param {YAML.Document} doc - The YAML Document of SEO.md (deprecated, but kept for signature compatibility)
 * @param {any} response - The API response from analyze/sync
 * @param {string} cwd - Current working directory
 */
export async function writeAnalysisToSeoMd(doc, response, cwd) {
    const lastAnalyzed = response.aeo_analysis.last_analyzed;
    const nextAnalysis = response.aeo_analysis.next_analysis;

    const statusData = {
        source: 'foxcite',
        last_analyzed: lastAnalyzed,
        next_analysis: nextAnalysis,
        aeo: {
            overall_citation_rate: response.aeo_analysis.overall_citation_rate,
            overall_gap_score: response.aeo_analysis.overall_gap_score,
            engines_tracked: response.aeo_analysis.engines_tracked,
        },
        intent: {},
        pages: {
            pages: response.page_analysis.map(p => ({
                id: p.id,
                url: p.url,
                citation_rate: p.citation_rate,
                gap_score: p.gap_score,
                top_cited_competitor: p.top_cited_competitor
            })),
            missing_pages: [],
            build_order_recommendation: []
        },
        keywords: {}
    };

    const categories = ['informational', 'comparison', 'transactional', 'reputational', 'category'];
    for (const cat of categories) {
        if (response.intent_analysis && response.intent_analysis[cat]) {
            statusData.intent[cat] = {
                citation_rate: response.intent_analysis[cat].citation_rate,
                top_cited_competitor: response.intent_analysis[cat].top_cited_competitor,
                gap_score: response.intent_analysis[cat].gap_score,
                trend: response.intent_analysis[cat].trend || 'stable'
            };
        }
    }

    const seomdDir = path.join(cwd, '.seo');
    await fs.ensureDir(seomdDir);
    const statusPath = path.join(seomdDir, 'STATUS.yml');
    
    const header = `# .seo/STATUS.yml\n#\n# This file is auto-generated by your connected SEO.md platform.\n# Do not edit manually — run \`npx seomd analyze\` to update.\n# Run \`npx seomd sync\` to pull latest intelligence.\n\n`;
    await fs.writeFile(statusPath, header + YAML.stringify(statusData), 'utf8');
}

/**
 * Generates and writes the .seo/REVERSE.md file.
 * 
 * @param {string} cwd - Current working directory
 * @param {any} response - The API response from analyze/sync
 */
export async function writeReverseMd(cwd, response, defaultDomain = 'example.com', defaultBrand = 'My Brand') {
    const seomdDir = path.join(cwd, '.seo');
    await fs.ensureDir(seomdDir);
    const reversePath = path.join(seomdDir, 'REVERSE.md');

    const reversePages = response.page_analysis.map(p => ({
        id: p.id,
        url: p.url,
        status: p.status || 'planned',
        citation_rate: p.citation_rate,
        gap_score: p.gap_score,
        top_cited_competitor: p.top_cited_competitor,
        why_page_won: p.why_page_won || [],
        citation_hooks: p.citation_hooks || [],
        gaps_for_my_brand: p.gaps_for_brand || [],
        remediation_playbook: p.remediation_playbook || [],
        fastest_win: p.fastest_win || { action: null, estimated_gap_score_improvement: null, effort: null },
        suggested_content_outline: p.suggested_content_outline || []
    }));

    const primaryCompetitor = response.intent_analysis?.comparison?.top_cited_competitor || 'None';

    const reverseDoc = {
        domain: response.domain || defaultDomain,
        brand: response.brand_name || defaultBrand,
        primary_competitor: primaryCompetitor,
        last_analyzed: response.aeo_analysis.last_analyzed,
        next_analysis: response.aeo_analysis.next_analysis,
        source: 'foxcite',
        pages: reversePages
    };

    const header = `# .seo/REVERSE.md\n#\n# This file is auto-generated by your connected SEO.md platform.\n# Do not edit manually — run \`npx seomd analyze\` to update.\n# Run \`npx seomd sync\` to pull latest intelligence.\n\n`;

    const yamlContent = YAML.stringify(reverseDoc);
    await fs.writeFile(reversePath, header + yamlContent, 'utf8');
}

/**
 * Writes individual page playbooks into .seo/pages/{id}.md files.
 * 
 * @param {string} cwd - Current working directory
 * @param {any} response - The API response from analyze/sync
 */
export async function writePageAnalysis(cwd, response) {
    const seomdDir = path.join(cwd, '.seo');
    const pagesDir = path.join(seomdDir, 'pages');

    await fs.ensureDir(pagesDir);

    for (const page of response.page_analysis) {
        if (page.markdown_content) {
            const filePath = path.join(pagesDir, `${page.id}.md`);
            await fs.writeFile(filePath, page.markdown_content, 'utf8');
        }
    }
}
